// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Dialog: typeof import('./src/components/dialog/index.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview/index.vue')['default']
    ImgUpload: typeof import('./src/components/imgUpload/index.vue')['default']
  }
}

export { }
